# Generated by Django 3.1.4 on 2021-02-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20210224_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profie_pic',
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/images/default.jpeg', null=True, upload_to=''),
        ),
    ]
